name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        uses: docker/setup-docker@v3

      - name: Build Docker image
        run: |
          docker build -t your-ecr-repository-name:latest .

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 402639326195.dkr.ecr.ap-south-1.amazonaws.com
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Docker image
        run: |
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest

      - name: Stop and remove existing container
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PEM_FILE }} ec2-user@your-ec2-instance-ip "docker stop travel-container-fe && docker rm travel-container-fe"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PEM_FILE }} ec2-user@your-ec2-instance-ip "docker run -d -p 3000:3000 402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest"
