name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io
          sudo apt-get -y install docker.io
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          sudo docker --version

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}\nregion=${{ secrets.AWS_REGION }}" > ~/.aws/config

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 402639326195.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t 402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest .

      - name: Push Docker image to ECR
        run: |
          docker push 402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build-and-deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}\nregion=${{ secrets.AWS_REGION }}" > ~/.aws/config

      - name: SSH Deploy to AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.PEM_FILE }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo chmod 666 /var/run/docker.sock
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 402639326195.dkr.ecr.ap-south-1.amazonaws.com
            docker pull 402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest
            docker stop travel-container-fe || true
            docker rm travel-container-fe || true
            if [ ! "$(docker ps -q -f name=travel-container-fe)" ]; then
              docker run -d -p 3000:3000 --restart always --name travel-container-fe 402639326195.dkr.ecr.ap-south-1.amazonaws.com/test:latest
            else
              docker start travel-container-fe
            fi
